apiVersion: v1
kind: Service
metadata:
   name: master-service
   labels:
     app: master-service
spec:
   type: NodePort
   ports:
     - port: 5001
       nodePort: 30000
   selector:
     app: master-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: slave-service
spec:
  type: NodePort
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
      nodePort:  30002
  selector:
    app: slave-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: slave2-service
spec:
  type: NodePort
  ports:
    - port: 5003
      protocol: TCP
      targetPort: 5003
      nodePort: 30003
  selector:
    app: slave2-deploy
